name: Production Pipeline

on:
  push:
    branches:
      - production

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (example)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to Production Server
      if: success()
      run: |
        echo "Deploying to production server..."
        # Add your production deployment commands here
