name: Deployment Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Development Server
        run: |
          echo "🚀 Deploying to development server..."
          # 🔧 Replace the line below with your actual deployment script
          # Example:
          # scp -r . user@your-server:/var/www/my-app
          # ssh user@your-server "cd /var/www/my-app && pm2 restart app"
